name: online_payments_repository
description: Package that takes care of the business logic of the Online Payments Example
publish_to: none

dependencies:
  online_payments_sdk:
    # When depending on this package from a real application you should use:
    #   online_payments_sdk: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../../../
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"